/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AssistantDrawer: typeof import('./src/components/assistant/AssistantDrawer.vue')['default']
    AuthShell: typeof import('./src/components/auth/AuthShell.vue')['default']
    BiVisuHeader: typeof import('./src/components/bi/BiVisuHeader.vue')['default']
    ChargingLogin: typeof import('./src/components/auth/ChargingLogin.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EmailVerifyDialog: typeof import('./src/components/auth/EmailVerifyDialog.vue')['default']
    ExpandableChartBlock: typeof import('./src/components/bi/ExpandableChartBlock.vue')['default']
    FourSBanner: typeof import('./src/components/home/FourSBanner.vue')['default']
    MrEchart: typeof import('./src/components/bi/MrEchart.vue')['default']
    NavbarTools: typeof import('./src/components/layout/NavbarTools.vue')['default']
    NavIcon: typeof import('./src/components/layout/NavIcon.vue')['default']
    NowUiPageCard: typeof import('./src/components/layout/NowUiPageCard.vue')['default']
    PredictDurationForm: typeof import('./src/components/predict/PredictDurationForm.vue')['default']
    PredictFeeForm: typeof import('./src/components/predict/PredictFeeForm.vue')['default']
    PredictPlatformForm: typeof import('./src/components/predict/PredictPlatformForm.vue')['default']
    PredictSocForm: typeof import('./src/components/predict/PredictSocForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionDateTimeFields: typeof import('./src/components/predict/SessionDateTimeFields.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
