-- Auto-generated by analytics/scripts/generate_v6_v7_seed.py
-- version: manual-v6v7-2026-07-13
USE charging_bigdata;

DELETE FROM t_voltage_current_relation;
INSERT INTO t_voltage_current_relation (record_hour, voltage_change_rate, current_change_rate) VALUES
('00', 0.061036, -0.019333), ('11', 0.004953, 0.0), ('12', 0.003634, 0.0), ('13', 0.008377, 0.0), ('14', 0.009168, 0.0);

DELETE FROM t_soc_temperature;
INSERT INTO t_soc_temperature (battery_status, avg_max_temperature, avg_min_temperature, var_max_temperature, var_min_temperature) VALUES
('idle', 32.881356, 31.0, 0.105461, 0.0), ('charging', 34.434059, 32.583867, 1.169044, 0.981739), ('discharging', 36.805755, 34.676259, 0.346941, 0.40945);
